# Generated by Django 3.2 on 2022-07-10 19:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darajatoken',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 10, 19, 31, 56, 453825, tzinfo=utc)),
        ),
    ]
