# Generated by Django 3.2 on 2022-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_darajatoken_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='darajatoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
