# Generated by Django 4.0.5 on 2022-07-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='receiver',
        ),
    ]
