# Generated by Django 4.0.5 on 2022-07-07 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sirenapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='sirenapp.driver'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='account_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctor',
            name='ambulance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_doctor', to='sirenapp.ambulance'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_account', to='sirenapp.customeraccount'),
        ),
        migrations.AddField(
            model_name='review',
            name='ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_reviews', to='sirenapp.ambulance'),
        ),
        migrations.AddField(
            model_name='review',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reviews', to='sirenapp.hospital'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='sirenapp.customeraccount'),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='sirenapp.hospital'),
        ),
    ]
