# Generated by Django 4.0.5 on 2022-07-01 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sirenapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='trans_date',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='sirenapp.customeraccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='account_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
