# Generated by Django 3.2 on 2022-07-08 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sirenapp', '0002_ambulance_driver_customeraccount_account_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='account_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_account', to='sirenapp.hospital'),
        ),
    ]
