# Generated by Django 4.0.5 on 2022-07-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0002_rename_trans_date_transaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='owner',
        ),
    ]
