# Generated by Django 4.0.5 on 2022-07-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0002_trip_destination_trip_pickup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_choice',
            field=models.CharField(choices=[('regular', 'regular'), ('premium', 'premium')], default='regular', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
