# Generated by Django 3.2 on 2022-07-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0003_auto_20220708_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='phone',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
