# Generated by Django 4.0.5 on 2022-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0003_alter_package_package_choice_alter_trip_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_choice',
            field=models.CharField(choices=[('regular', 'regular'), ('premium', 'premium')], default='regular', max_length=200),
        ),
    ]
