# Generated by Django 4.0.5 on 2022-07-01 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sirenapp', '0004_hospital_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='owner',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_account', to='sirenapp.hospital'),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='account_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
