# Generated by Django 4.0.5 on 2022-06-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0005_alter_hospital_ambulances_alter_hospital_doctors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='ambulances',
            field=models.ManyToManyField(blank=True, related_name='ambulances', to='sirenapp.ambulance'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='sirenapp.doctor'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='sirenapp.review'),
        ),
    ]
