# Generated by Django 4.0.5 on 2022-07-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0005_remove_hospital_owner_customeraccount_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_driver', to='sirenapp.ambulance'),
        ),
    ]
