# Generated by Django 3.2 on 2022-07-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0006_auto_20220711_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
