# Generated by Django 4.0.5 on 2022-07-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0006_alter_driver_ambulance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='ambulances',
            field=models.ManyToManyField(blank=True, null=True, related_name='hospital_ambulances', to='sirenapp.ambulance'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='sirenapp.hospital'),
        ),
    ]
