# Generated by Django 4.0.5 on 2022-06-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0008_alter_review_ambulance_alter_review_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='rating',
        ),
    ]
