# Generated by Django 4.0.5 on 2022-07-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0010_rename_availability_ambulance_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='sirenapp.review'),
        ),
    ]
