# Generated by Django 4.0.5 on 2022-07-01 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0011_ambulance_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='sirenapp.driver'),
        ),
    ]
