# Generated by Django 4.0.5 on 2022-07-01 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0012_ambulance_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='ambulance',
        ),
    ]
