# Generated by Django 4.0.5 on 2022-07-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0013_remove_driver_ambulance'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='trips',
            field=models.ManyToManyField(blank=True, related_name='trips', to='sirenapp.trip'),
        ),
    ]
