# Generated by Django 4.0.5 on 2022-07-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0014_driver_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_choice',
            field=models.CharField(choices=[('1', 'Regular'), ('2', 'Premium')], default='regular', max_length=200),
        ),
    ]
