# Generated by Django 4.0.5 on 2022-06-30 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0003_ambulance_customeraccount_doctor_driver_hospital_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=255)),
                ('phone1', models.CharField(max_length=255)),
                ('phone2', models.CharField(blank=True, max_length=255, null=True)),
                ('phone3', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(max_length=55)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='client',
        ),
        migrations.RemoveField(
            model_name='users',
            name='service_provider',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('medical_conditions', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact', models.ManyToManyField(related_name='emergency_contact', to='accounts.emergencycontact')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sirenapp.package')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
