# Generated by Django 3.2 on 2022-07-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emergencycontact_patient_patientprofile_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='last_name',
        ),
    ]
