# Generated by Django 4.0.5 on 2022-07-06 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0015_alter_package_package_choice'),
        ('accounts', '0002_patientprofile_package_patientprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='emergency_contact',
            new_name='emergency_contacts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='id_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='sirenapp.customeraccount'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(default='sdfs', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='id_number',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(default='dfsdf', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='picture',
            field=models.ImageField(default='images/avatar_wqbvxp.svg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='dfd', max_length=150, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='dff', max_length=150, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='dfd', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
