# Generated by Django 4.0.5 on 2022-07-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('accounts', '0002_user_username'),
    ]

    operations = [
    ]
