# Generated by Django 4.0.5 on 2022-06-30 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sirenapp', '0004_hospital_account'),
        ('accounts', '0002_emergencycontact_remove_users_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sirenapp.customeraccount'),
        ),
    ]
