# Generated by Django 4.0.5 on 2022-07-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contacts',
            field=models.ManyToManyField(blank=True, related_name='emergency_contact', to='accounts.emergencycontact'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='id_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
