# Generated by Django 4.0.5 on 2022-07-06 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patientprofile_emergency_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient_emergency', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
